# Generated by Django 6.0.3 on 2026-04-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_category_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_savings_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal_mode',
            field=models.CharField(choices=[('Freestyle', 'Freestyle'), ('Balanced', 'Balanced'), ('Savings', 'Savings'), ('Custom', 'Custom')], default='Balanced', max_length=20),
        ),
    ]
