# Generated by Django 6.0.3 on 2026-04-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_custom_savings_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='savings_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
