# Generated by Django 6.0.3 on 2026-04-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_goal_weeklycategorybudget_weeklypledge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='amount_saved',
        ),
        migrations.RemoveField(
            model_name='weeklycategorybudget',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='weeklycategorybudget',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='weeklypledge',
            name='created_at',
        ),
        migrations.AddField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal_piggybank_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Accumulated savings earmarked for the Goals queue.', max_digits=12),
        ),
        migrations.AddField(
            model_name='weeklypledge',
            name='savings_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Populated after settlement if the user saved money.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='weeklycategorybudget',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
