# Generated by Django 6.0.3 on 2026-04-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_goal_options_remove_goal_amount_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='general_pledge_savings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cumulative savings from weekly pledges settled into General Savings.', max_digits=12),
        ),
    ]
