# Generated by Django 6.0.3 on 2026-04-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_general_pledge_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypledge',
            name='destination',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('piggybank', 'Piggybank')], help_text='Where the savings were routed upon settlement.', max_length=20, null=True),
        ),
    ]
