# Generated by Django 6.0.3 on 2026-04-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_weeklypledge_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklypledge',
            name='destination',
        ),
    ]
